name: Test Periodico

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17' 

      - name: Build and Test
        run: |        
           mvn test
