name: Backup del Repositorio
on:
  schedule:
    - cron: "0 0 * * 0" # Corre cada domingo a medianoche
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Archive Repository
        run: zip -r backup.zip .
      - name: Upload Backup
        uses: actions/upload-artifact@v3
        with:
          name: backup
          path: backup.zip
