name: Configurar MySQL Remoto

on:
  push:
    branches:
      - main  

jobs:
  configurar-mysql:
    runs-on: windows-latest
    steps:
    - name: Checkout repositorio
      uses: actions/checkout@v2

    - name: Configurar MySQL para acceso remoto
      run: |
        chmod +x configurar_mysql_remoto.sh
        ./configurar_mysql_remoto.sh
