name: Chequeo de Licencias
on:
   schedule:
    - cron: "0 8 * * 1"
jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Chequeo de Licencias
        run: npm run license-check
